/**
 * @file vl53l8cx_uld_platform.h
 * @brief VL53L8CX Platform Abstraction Layer Implementation
 *
 * This file contains implementations of the platform abstraction
 * layer for the VL53L8CX. 
 *
 * @author WilliTourt willitourt@foxmail.com
 * @version 1.1
 * @date 2026.02.23
 * 
 * @note Comments are mostly generated by AI. 
 *       Code has only tested iic part.
 * 
 * @changelog:
 * - 2025.12.09: Initial release
 * - 2026.02.23: Fixed IIC communication timeout error, now IIC@400kHz is stable.
 * 
 */

#ifndef _VL53L8CX_ULD_PLATFORM_H_
#define _VL53L8CX_ULD_PLATFORM_H_

#include <stdint.h>
#include <string.h>

#include "main.h"

#if !defined(__STM32F1xx_HAL_H) && \
    !defined(__STM32F4xx_HAL_H) && \
    !defined(__STM32F7xx_HAL_H) && \
    !defined(__STM32H7xx_HAL_H) && \
    !defined(__STM32L4xx_HAL_H) && \
    !defined(__STM32G0xx_HAL_H) && \
    !defined(__STM32WBxx_HAL_H) && \
    !defined(__STM32WLxx_HAL_H)
#error "This vl53l8cx library can only be used with STM32Cube HAL drivers"
#endif

#if !defined(HAL_I2C_MODULE_ENABLED) && \
    !defined(HAL_SPI_MODULE_ENABLED)
#error "At least one IIC port or SPI port should be opened"
#endif


typedef enum {
	VL53L8CX_COMMS_I2C,  /**< Use I2C communication interface */
	VL53L8CX_COMMS_SPI   /**< Use SPI communication interface */
} VL53L8CX_CommsType;

/**
 * @brief Structure VL53L8CX_Platform needs to be filled by the customer,
 * depending on his platform. At least, it contains the VL53L8CX I2C address.
 * Some additional fields can be added, as descriptors, or platform
 * dependencies. Anything added into this structure is visible into the platform
 * layer.
 */
typedef struct {
	#ifdef HAL_I2C_MODULE_ENABLED
	I2C_HandleTypeDef*    hi2c;        /**< I2C handle pointer (when using I2C communication) */
	uint8_t  			  i2c_addr;    /**< I2C device address (7-bit address) */
	#endif

	#ifdef HAL_SPI_MODULE_ENABLED
	SPI_HandleTypeDef*    hspi;        /**< SPI handle pointer (when using SPI communication) */
	GPIO_TypeDef*         cs_port;     /**< GPIO port for chip select pin (SPI mode) */
	uint8_t               cs_pin;      /**< GPIO pin number for chip select (SPI mode) */
	#endif

	VL53L8CX_CommsType    comms_type;  /**< Communication interface type (I2C or SPI) */

	GPIO_TypeDef*         reset_port;  /**< GPIO port for sensor reset pin */
	uint8_t               reset_pin;   /**< GPIO pin number for sensor reset */

	GPIO_TypeDef*         interrupt_port;  /**< GPIO port for interrupt pin */
	uint8_t               interrupt_pin;   /**< GPIO pin number for interrupt */

	uint8_t               pwr_mode;    /**< Power mode configuration */

	uint8_t 			  resolution;  /**< Sensor resolution (4x4 or 8x8 zones) */
	uint8_t               ranging_freq_hz; /**< Ranging frequency in Hz */
	uint8_t               ranging_mode;    /**< Ranging mode configuration */

	uint32_t              integrations_period_ms; /**< Integration period in milliseconds */
	uint8_t               sharpener_percent;      /**< Sharpener percentage (0-100%) */
	uint8_t               target_order;           /**< Target order configuration */

	uint8_t               is_sync_pin_enabled;    /**< Sync pin enable flag */

	uint32_t              VHV_repeat_cnt;         /**< VHV repeat count configuration */

} VL53L8CX_Platform;

/** Platform function return status codes */
#define VL53L8CX_PLATFORM_OK 			((uint8_t) 0U)      /**< Operation completed successfully */
#define VL53L8CX_PLATFORM_TIMEOUT_ERROR ((uint8_t) 1U)      /**< Communication timeout error */
#define VL53L8CX_PLATFORM_INVALID_PARAM ((uint8_t) 127U)    /**< Invalid parameter error */
#define VL53L8CX_PLATFORM_STATUS_ERROR 	((uint8_t) 255U)    /**< General status error */

/** Communication timeout value (uses HAL maximum delay) */
#define VL53L8CX_COMM_TIMEOUT_MS HAL_MAX_DELAY

/*
 * @brief The macro below is used to define the number of target per zone sent
 * through I2C. This value can be changed by user, in order to tune I2C
 * transaction, and also the total memory size (a lower number of target per
 * zone means a lower RAM). The value must be between 1 and 4.
 */

#define 	VL53L8CX_NB_TARGET_PER_ZONE		1U

/*
 * @brief The macro below can be used to avoid data conversion into the driver.
 * By default there is a conversion between firmware and user data. Using this macro
 * allows to use the firmware format instead of user format. The firmware format allows
 * an increased precision.
 */

// #define 	VL53L8CX_USE_RAW_FORMAT

/*
 * @brief All macro below are used to configure the sensor output. User can
 * define some macros if he wants to disable selected output, in order to reduce
 * I2C access.
 */

// #define VL53L8CX_DISABLE_AMBIENT_PER_SPAD
// #define VL53L8CX_DISABLE_NB_SPADS_ENABLED
// #define VL53L8CX_DISABLE_NB_TARGET_DETECTED
// #define VL53L8CX_DISABLE_SIGNAL_PER_SPAD
// #define VL53L8CX_DISABLE_RANGE_SIGMA_MM
// #define VL53L8CX_DISABLE_DISTANCE_MM
// #define VL53L8CX_DISABLE_REFLECTANCE_PERCENT
#define VL53L8CX_DISABLE_TARGET_STATUS      /**< Disable target status output to reduce I2C data */
#define VL53L8CX_DISABLE_MOTION_INDICATOR   /**< Disable motion indicator output to reduce I2C data */

/**
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @param (uint16_t) Address : I2C location of value to read.
 * @param (uint8_t) *p_values : Pointer of value to read.
 * @return (uint8_t) status : 0 if OK
 */
uint8_t VL53L8CX_RdByte(
		VL53L8CX_Platform *p_platform,
		uint16_t RegisterAdress,
		uint8_t *p_value);

/**
 * @brief Mandatory function used to write one single byte.
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @param (uint16_t) Address : I2C location of value to read.
 * @param (uint8_t) value : Pointer of value to write.
 * @return (uint8_t) status : 0 if OK
 */
uint8_t VL53L8CX_WrByte(
		VL53L8CX_Platform *p_platform,
		uint16_t RegisterAdress,
		uint8_t value);

/**
 * @brief Mandatory function used to read multiples bytes.
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @param (uint16_t) Address : I2C location of values to read.
 * @param (uint8_t) *p_values : Buffer of bytes to read.
 * @param (uint32_t) size : Size of *p_values buffer.
 * @return (uint8_t) status : 0 if OK
 */
uint8_t VL53L8CX_RdMulti(
		VL53L8CX_Platform *p_platform,
		uint16_t RegisterAdress,
		uint8_t *p_values,
		uint32_t size);

/**
 * @brief Mandatory function used to write multiples bytes.
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @param (uint16_t) Address : I2C location of values to write.
 * @param (uint8_t) *p_values : Buffer of bytes to write.
 * @param (uint32_t) size : Size of *p_values buffer.
 * @return (uint8_t) status : 0 if OK
 */
uint8_t VL53L8CX_WrMulti(
		VL53L8CX_Platform *p_platform,
		uint16_t RegisterAdress,
		uint8_t *p_values,
		uint32_t size);

/**
 * @brief Optional function, only used to perform an hardware reset of the
 * sensor. This function is not used in the API, but it can be used by the host.
 * This function is not mandatory to fill if user don't want to reset the
 * sensor.
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @return (uint8_t) status : 0 if OK
 */
uint8_t VL53L8CX_Reset_Sensor(
		VL53L8CX_Platform *p_platform);

/**
 * @brief Mandatory function, used to swap a buffer. The buffer size is always a
 * multiple of 4 (4, 8, 12, 16, ...).
 * @param (uint8_t*) buffer : Buffer to swap, generally uint32_t
 * @param (uint16_t) size : Buffer size to swap
 */
void VL53L8CX_SwapBuffer(
		uint8_t 		*buffer,
		uint16_t 	 	 size);

/**
 * @brief Mandatory function, used to wait during an amount of time. It must be
 * filled as it's used into the API.
 * @param (VL53L8CX_Platform*) p_platform : Pointer of VL53L8CX platform
 * structure.
 * @param (uint32_t) TimeMs : Time to wait in ms.
 * @return (uint8_t) status : 0 if wait is finished.
 */
uint8_t VL53L8CX_WaitMs(
		VL53L8CX_Platform *p_platform,
		uint32_t TimeMs);

#endif	// _VL53L8CX_ULD_PLATFORM_H_
