/**
 * @file vl53l8cx.h
 * @brief VL53L8CX Time-of-Flight sensor C++ wrapper class
 *
 * This header file defines the C++ interface for the VL53L8CX multi-zone
 * Time-of-Flight sensor. It provides a convenient object-oriented API
 * on top of the underlying C driver, supporting both I2C and SPI communication.
 *
 * @author WilliTourt willitourt@foxmail.com
 * @version 1.0
 * @date 2026.02.23
 * 
 * @note Comments are mostly generated by AI. 
 * 
 * @changelog:
 * - 2025.12.09: Initial release
 * 
 */

#pragma once

extern "C" {

#include "vl53l8cx_uld_platform.h"
#include "vl53l8cx_api.h"

}



class VL53L8CX {
    public:

	/** Operation status codes */
	enum class Status : uint8_t {
		OK = VL53L8CX_STATUS_OK,                     /**< Operation successful */
		TIMEOUT = VL53L8CX_STATUS_TIMEOUT_ERROR,     /**< Communication timeout */
		CORRUPTED_FRAME = VL53L8CX_STATUS_CORRUPTED_FRAME, /**< Corrupted data frame */
		LASER_SAFETY = VL53L8CX_STATUS_LASER_SAFETY, /**< Laser safety error */
		XTALK_FAILED = VL53L8CX_STATUS_XTALK_FAILED, /**< Crosstalk calibration failed */
		FW_CHECKSUM_FAIL = VL53L8CX_STATUS_FW_CHECKSUM_FAIL, /**< Firmware checksum error */
		MCU_ERROR = VL53L8CX_MCU_ERROR,              /**< MCU internal error */
		INVALID_PARAM = VL53L8CX_STATUS_INVALID_PARAM, /**< Invalid parameter */
		ERROR = VL53L8CX_STATUS_ERROR                /**< General error */
	};

        #ifdef HAL_I2C_MODULE_ENABLED
        /** I2C constructor */
        VL53L8CX(I2C_HandleTypeDef *hi2c, uint8_t i2c_address = VL53L8CX_DEFAULT_I2C_ADDRESS);
        #endif
        #ifdef HAL_SPI_MODULE_ENABLED
        /** SPI constructor */
        VL53L8CX(SPI_HandleTypeDef *hspi, GPIO_TypeDef *CS_GPIOx, uint8_t CS_Pin);
        #endif

        /** Initialize sensor */
        Status begin();

        /** Check if sensor is responsive */
        bool isAlive();
        #if defined(HAL_I2C_MODULE_ENABLED)
        /** Change I2C address */
        Status setIICAddress(uint16_t i2c_address);
        #endif

        /** Start continuous ranging */
        Status startRanging();
        /** Stop ranging */
        Status stopRanging();
        /** Check if new data is available */
        bool dataReady();

        /* Communication/read helpers: call underlying C API and update internal cache */
        /** Get ranging data and copy to provided buffer */
        Status getRangingData(VL53L8CX_ResultsData *p_results); /* fills internal _results and immediately get it */
        /** Update internal results cache */
        Status readRangingData(); /* only updates internal _results */

        /** Get current resolution (4x4 or 8x8) */
        inline uint8_t  getResolution() const         { return _cfg.platform.resolution;                }
        /** Get ranging frequency in Hz */
        inline uint8_t  getRangingFrequencyHz() const { return _cfg.platform.ranging_freq_hz;           }
        /** Get ranging mode */
        inline uint8_t  getRangingMode() const        { return _cfg.platform.ranging_mode;              }
        /** Get integration time in ms */
        inline uint32_t getIntegrationTimeMs() const  { return _cfg.platform.integrations_period_ms;    }
        /** Get sharpener percentage */
        inline uint8_t  getSharpenerPercent() const   { return _cfg.platform.sharpener_percent;         }
        /** Get target order */
        inline uint8_t  getTargetOrder() const        { return _cfg.platform.target_order;              }
        /** Check if sync pin is enabled */
        inline bool     isSyncPinEnabled() const      { return (bool)_cfg.platform.is_sync_pin_enabled; }
        /** Get VHV repeat count */
        inline uint32_t getVHVRepeatCount() const     { return _cfg.platform.VHV_repeat_cnt;            }

        /** Get reference to results data */
        inline const VL53L8CX_ResultsData& results() const { return _results; }

        /** Refresh settings from sensor */
        Status refreshSettings(); /* updates platform fields (resolution, freq, integration time, etc.) */

        /** DCI read operation */
        Status dciReadData(uint8_t *data, uint32_t index, uint16_t data_size);
        /** DCI write operation */
        Status dciWriteData(uint8_t *data, uint32_t index, uint16_t data_size);
        /** DCI replace data */
        Status dciReplaceData(uint8_t *data, uint32_t index, uint16_t data_size,
                              uint8_t *new_data, uint16_t new_data_size, uint16_t new_data_pos);

        /** Get configuration pointer */
        VL53L8CX_Configuration *getConfig() { return &_cfg; }

        /* Single-value getters from cached results. Each returns the value and
         * sets `ok` to true when the index is valid, false otherwise. */
        /** Get distance in mm for specific zone and target */
        int16_t  getDistanceMm(uint8_t zone, uint8_t target_idx, bool &ok) const;
        /** Get range sigma in mm */
        uint16_t getRangeSigmaMm(uint8_t zone, uint8_t target_idx, bool &ok) const;
        /** Get signal per SPAD */
        uint32_t getSignalPerSpad(uint8_t zone, uint8_t target_idx, bool &ok) const;
        /** Get reflectance percentage */
        uint8_t  getReflectancePercent(uint8_t zone, uint8_t target_idx, bool &ok) const;
        /** Get target status */
        uint8_t  getTargetStatus(uint8_t zone, uint8_t target_idx, bool &ok) const;

        /** Get ambient per SPAD for zone */
        uint32_t getAmbientPerSpad(uint8_t zone, bool &ok) const;
        /** Get number of targets detected in zone */
        uint8_t  getNbTargetDetected(uint8_t zone, bool &ok) const;
        /** Get number of SPADs enabled in zone */
        uint32_t getNbSpadsEnabled(uint8_t zone, bool &ok) const;

        /* Motion indicator getters (if enabled). `motion_idx` range: 0..31 */
        /** Get motion indicator value */
        uint32_t getMotion(uint8_t motion_idx, bool &ok) const;
        /** Get motion global indicator 1 */
        uint32_t getMotionGlobalIndicator1(bool &ok) const;
        /** Get motion global indicator 2 */
        uint32_t getMotionGlobalIndicator2(bool &ok) const;
        /** Get motion status */
        uint8_t  getMotionStatus(bool &ok) const;
        /** Get number of detected motion aggregates */
        uint8_t  getMotionNbOfDetectedAggregates(bool &ok) const;

    private:
        VL53L8CX_Configuration _cfg;      /**< Sensor configuration */
        VL53L8CX_ResultsData _results;    /**< Cached ranging results */

};
